#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes.
#
version: "3.3"

services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
            - type: bind
              source: ./scrape-targets
              target: /prometheus/targets
        restart: always
        ports:
            - 9090:9090
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        restart: always
        ports:
            - 3000:3000

volumes:
    grafana-data:
    prometheus-data:
    targets:
